"""create user and blog table migrations

Revision ID: 04983d14a50b
Revises: 
Create Date: 2024-08-11 14:34:47.262499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04983d14a50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
